# Generated by Django 5.1.2 on 2024-11-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='Date_time',
            field=models.DateField(),
        ),
    ]
