# Generated by Django 5.1.2 on 2024-11-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_records_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='Date_time',
            field=models.DateTimeField(),
        ),
    ]
