# Generated by Django 5.1.2 on 2024-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_records_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='close',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='records',
            name='high',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='records',
            name='low',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='records',
            name='open',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
